### ISSUE TITLE
Does This Project Not Work Out Of The Box?

### ISSUE THREAD

**Issue by kixago** [apollographql/gatsby-theme-apollo#95]
I have been trying to get app-docs working for the better part of two days now somewhat unsuccessfully.

While I have been able too compile and get a localhost running, I am not very efficient in Gatsby. 

1st problem: This project required you select a defaultVersion of 2 and also required you too place  a versions {'1': 'version-1'} or it will not compile. If you select the default to 2, it will allow you too switch between versions but as of yet I have not been able too figure out how to use this project without versioning. If you select version 1, it is pulling information from somewhere on the web and compiling .. Version 2 allows me too start editing how I wish but why do I need too have a version at all? 

Another thing is in the page-content.js if you remove the Github sidebar link the whole project fails miserably. I just want too hide it ... 

I have also been unable too figure out how too add menu links on the top Navbar next to the search box.

This is a very nice and promising theme but some direction would be great. I have followed your documentation extensively but it seems to be lacking somewhere for people like me.

Thanks in advance for anyone who can help.

**Comment by trevorblades** [comment]
I just merged #96 which aims to make a better "out of the box" experience with this theme. I wanted to make it more clear which options where required to make the theme work by adding a "required" column to the [options table in the readme](https://github.com/apollographql/gatsby-theme-apollo/tree/master/packages/gatsby-theme-apollo-docs#options).

I also just [made a change](https://github.com/apollographql/gatsby-theme-apollo/commit/97341da243ecd9fc7116ba5681219181ca397cdc) that hides the "Edit on GitHub" link if the `githubRepo` option is omitted in your theme configuration.

I put together [an example](https://codesandbox.io/s/gatsby-theme-apollo-docs-hello-world-bywp2) on CodeSandbox that shows the smallest configuration possible to get the them up and running. Hope that helps answer your questions, and if you run into any other issues please let us know!

**Comment by kixago** [comment]
Thanks for your prompt feedback. With your modifications, I was able too get the site running and set up mostly. And, after looking through different files, I am starting too see how Gatsby and this theme work. However, I still lack clarification on a few key facts:

1. If I want too remove the launch graph manager link in the header-button.js would I edit that directly if I wanted too replace it with say Home, About, Faq, etc.? If so, every time I yarn upgrade my changes would be gone. Just curious if a better way is available.

2. On your doc site, when you select a navConfig menu, it shows in the top left corner as active. In other words, if you select the iOS docs, that is what is displayed to the user as the active "main" menu. On mine however, it always shows the first one ("basic") regardless of the page I have active. 

3. Another important find on your site is your sidebarCategories change depending on the subdirectory the user is currently on. So if someone chose the iOS navConfig, your sidebarCategories update accordingly and link to the proper tutorial .. Exactly what I'm looking for. Currently, mine are always visible regardless of the markdown file/directory I am in. I have a feeling I am missing an identifier or something unclear to me.

4. Is it possible to add a footer at the bottom of the page without meddling in the JS files? Just curious.

Appreciate the excellent work and effort it took to make this theme. I am really enjoying it now that I got it working and hope you can help me clarify these small tasks that would really make this theme pop for me. I appreciate any time you may set aside too answer my questions.

**Comment by trevorblades** [comment]
I'll respond to your questions in order:

1. To change the `HeaderButton`, you can use component shadowing as I've done in the example that I linked in the previous comment. Create a file that exports a React component at `src/gatsby-theme-apollo-docs/components/header-button.js`. This component can contain any content that you want.
2. Apollo's documentation site is actually multiple separate Gatsby sites, each with their own theme configuration. The "active" menu text is actually the text configured by the `subtitle` or `siteName` theme options, as you can see [in this file](https://github.com/apollographql/gatsby-theme-apollo/blob/master/packages/gatsby-theme-apollo-docs/src/components/page-layout.js#L177-L179).
3. Similar to the answer above, each site has [its own `sidebarCategories` configuration](https://github.com/apollographql/apollo-client/blob/master/docs/gatsby-config.js), and then the sites are deployed next to one another making it appear as if it's one continuous website.
4. I just released a new version of the theme that adds a shadowable `Footer` component to the bottom of the theme's `Template` screen. Since we don't use a footer at Apollo, the theme's `Footer` component just returns `null`. If you want to set a custom footer, simply shadow this component by creating a file at `src/gatsby-theme-apollo-docs/components/footer.js` and write your custom React component in there.

Hopefully this helps!
